name: angular_dart_example
version: 0.0.1
dependencies:
  angular:
    path: ../
  browser: any
  unittest: any
  quiver: any
  web_components: any

transformers:
- angular:
    html_files:
      - web/bouncing_controller.html
      - web/form_controller.html
