name: angular
version: 0.9.10
authors:
- Misko Hevery <misko@hevery.com>
- Pavel Jbanov <pavelgj@gmail.com>
- James deBoer <james@huronbox.com>
- Chirayu Krishnappa <chirayu@google.com>
- Matias Niemela <matias@yearofmoo.com>
- Paul Rohde <paul@paulrohde.com>
- Victor Berchet <victor@suumit.com>
description: Angular for dart.
homepage: https://angulardart.org
environment:
  sdk: '>=1.2.0'
dependencies:
  analyzer: '>=0.13.0 <0.14.0'
  barback: '>=0.11.1 <0.14.0'
  browser: '>=0.10.0 <0.11.0'
  code_transformers: '>=0.1.3 <0.2.0'
  collection: '>=0.9.1 <1.0.0'
  di:
    git:
      url: git://github.com/angular/di.dart.git
  html5lib: '>=0.9.2 <0.10.0'
  intl: '>=0.8.7 <0.10.0'
  perf_api: '>=0.0.8 <0.1.0'
  route_hierarchical: '>=0.4.18 <0.5.0'
  shadow_dom: '>=0.9.1 <1.0.0'
dev_dependencies:
  benchmark_harness: '>=1.0.0'
  unittest: '>=0.10.1 <0.12.0'
  mock: '>=0.10.0 <0.12.0'
