name: angular
version: 0.0.6
authors:
- Misko Hevery <misko@hevery.com>
- Pavel Jbanov <pavelgj@gmail.com>
- James deBoer <james@huronbox.com>
- Chirayu Krishnappa <chirayu@google.com>
homepage: https://github.com/angular/angular.dart
description:
  Angular for dart.

dependencies:
  analyzer_experimental: any
  browser: any
  di: any
  html5lib: any
  intl: any
  js: any
  meta: any
  perf_api: any
  route_hierarchical: any
  unittest: any
