name: angular
version: 0.9.8
authors:
- Misko Hevery <misko@hevery.com>
- Pavel Jbanov <pavelgj@gmail.com>
- James deBoer <james@huronbox.com>
- Chirayu Krishnappa <chirayu@google.com>
- Matias Niemela <matias@yearofmoo.com>
- Paul Rohde <paul@paulrohde.com>
description: Angular for dart.
homepage: https://angulardart.org
environment:
  sdk: '>=1.2.0'
dependencies:
  analyzer: '>=0.10.0 <0.12.0'
  browser: '>=0.8.7 <0.10.0'
  collection: '>=0.9.1 <1.0.0'
  di: '>=0.0.32 <0.1.0'
  html5lib: '>=0.8.7 <0.10.0'
  intl: '>=0.8.7 <0.10.0'
  perf_api: '>=0.0.8 <0.1.0'
  route_hierarchical: '>=0.4.7 <0.5.0'
  shadow_dom: '>=0.9.1 <1.0.0'
dev_dependencies:
  benchmark_harness: '>=1.0.0'
  hop: '>=0.30.2 <1.0.0'
  unittest: '>=0.8.7 <0.10.0'
