name: angular
version: '1.1.1'
authors:
- Misko Hevery <misko@hevery.com>
- Pavel Jbanov <pavelgj@gmail.com>
- James deBoer <james@huronbox.com>
- Chirayu Krishnappa <chirayu@google.com>
- Matias Niemela <matias@yearofmoo.com>
- Paul Rohde <paul@paulrohde.com>
- Victor Berchet <victor@suumit.com>
- Rado Kirov <radokirov@google.com>
description: Angular for dart.
homepage: https://angulardart.org
environment:
  sdk: '>=1.4.0'
dependencies:
  analyzer: '>=0.24.0 <0.25.0'
  args: '>=0.12.0 <0.13.0'
  barback: '>=0.13.0 <0.17.0'
  browser: '>=0.10.0 <0.11.0'
  code_transformers: '>=0.2.7 <0.3.0'
  collection: '>=1.1.0 <1.2.0'
  di: '>=3.3.3 <4.0.0'
  html5lib: '>=0.12.0 <0.13.0'
  intl: '>=0.8.7 <0.12.0'
  observe: '>=0.12.0 <0.14.0'
  perf_api: '>=0.0.9 <0.1.0'
  route_hierarchical: '>=0.6.1 <0.7.0'
dev_dependencies:
  benchmark_harness: '>=1.0.0 <2.0.0'
  guinness: '>=0.1.9 <0.2.0'
  mock: '>=0.10.0 <0.12.0'
  protractor: '0.0.5'
  unittest: '>=0.10.1 <0.12.0'
  web_components: '>=0.11.1 <0.12.0'
  browser_detect: '>=1.0.3 <2.0.0'
